{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "annotation-1.9.0-multiplatform-sources.jar",
          "url": "annotation-1.9.0-multiplatform-sources.jar",
          "size": 73768,
          "sha512": "203e646abc49aa9a6d582e5f1ea376437d9053173f6e9340fef8eea935b2ba4abce2b9e157af8e3151ebbe9bdd04da001ae5d35655cc7a911744a7c8d0155fec",
          "sha256": "b693afd398bcb9ce30fd7f38ae53700ff187050dd1cfdacd9fdd43c5ddac1f5d",
          "sha1": "c4818345ffdb8436d0507275485b8e25facd03e3",
          "md5": "fbed74e92b94f5387d27ffccdd773a77"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "annotation-1.9.0-versionMetadata.json",
          "size": 10678,
          "sha512": "8068e9a0ce4ace1bb9ba4c302fd45b7546313644a7e8c58bdf571f0dd776494364e801b75090cc012f1ad9c680c228bb50e615b9dbb6ad1fdb24295ca6fad483",
          "sha256": "0d299e1d6c95aff40ec427fe226b7a8b933281290f346ff4f9775fa4c5e154ad",
          "sha1": "05d6ccae4c93baf5c027134ddb15bc84aa9b7a50",
          "md5": "cdd620d5481a9de4a8c8c5ff958579b6"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-metadata-1.9.0.jar",
          "url": "annotation-1.9.0.jar",
          "size": 11570,
          "sha512": "623e3c867b78c5b8ef2bd31cfe8cb2ce19816a423103724dbaf5bcb459a77e9b377468410ecc721b803fcb31c1eefc526dc387b90304fab045a33b9a18e450d4",
          "sha256": "e0982a8ca91a0e4ebf9a17b51c98424008ce0aaac345c5c3746d143838d8bba7",
          "sha1": "3aae5e9e851bba9e260ddf6a41e2e3188d22291d",
          "md5": "4e76af7107c3056bbc2a930c0bb8ffb1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "annotation-kotlin-1.9.0-sources.jar",
          "url": "annotation-1.9.0-sources.jar",
          "size": 29195,
          "sha512": "8bd77064aaa1e079a45f982fbdc5565a3efc3e26adc66363146de279087e27afc1e62f188fe6c0d82da585ab05f651f77f70d6db26dac9bbd0718efc1d57813d",
          "sha256": "4560d6790c5174f4a6f1170fd8bd4c38ad918608fedd624fb67a35cd1a0f4e3a",
          "sha1": "b4b206cb9f956d7abf27fd8c95ec1f6dcdc5a4d6",
          "md5": "9772cec615ad89e9be417ed0522b41e6"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm32/1.9.0/annotation-androidnativearm32-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm32/1.9.0/annotation-androidnativearm32-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm64/1.9.0/annotation-androidnativearm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm64/1.9.0/annotation-androidnativearm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex64/1.9.0/annotation-androidnativex64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex64/1.9.0/annotation-androidnativex64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex86/1.9.0/annotation-androidnativex86-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex86",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex86/1.9.0/annotation-androidnativex86-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex86",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.9.0/annotation-iosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.9.0/annotation-iosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.9.0/annotation-iosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.9.0/annotation-iossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.9.0/annotation-iossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.9.0/annotation-iossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.9.0/annotation-iosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.9.0/annotation-iosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.9.0/annotation-iosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.9.0/annotation-jvm-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.9.0/annotation-jvm-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.9.0/annotation-jvm-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxarm64/1.9.0/annotation-linuxarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxarm64/1.9.0/annotation-linuxarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxx64/1.9.0/annotation-linuxx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxx64/1.9.0/annotation-linuxx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.9.0/annotation-macosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.9.0/annotation-macosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.9.0/annotation-macosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.9.0/annotation-macosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.9.0/annotation-macosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.9.0/annotation-macosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-mingwx64/1.9.0/annotation-mingwx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-mingwx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-mingwx64/1.9.0/annotation-mingwx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-mingwx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosarm64/1.9.0/annotation-tvosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosarm64/1.9.0/annotation-tvosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosarm64/1.9.0/annotation-tvosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvossimulatorarm64/1.9.0/annotation-tvossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvossimulatorarm64/1.9.0/annotation-tvossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvossimulatorarm64/1.9.0/annotation-tvossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosx64/1.9.0/annotation-tvosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosx64/1.9.0/annotation-tvosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosx64/1.9.0/annotation-tvosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../annotation-wasm-js/1.9.0/annotation-wasm-js-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../annotation-wasm-js/1.9.0/annotation-wasm-js-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../annotation-wasm-js/1.9.0/annotation-wasm-js-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm32/1.9.0/annotation-watchosarm32-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm32/1.9.0/annotation-watchosarm32-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm32/1.9.0/annotation-watchosarm32-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm64/1.9.0/annotation-watchosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm64/1.9.0/annotation-watchosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm64/1.9.0/annotation-watchosarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosdevicearm64/1.9.0/annotation-watchosdevicearm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosdevicearm64/1.9.0/annotation-watchosdevicearm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosdevicearm64/1.9.0/annotation-watchosdevicearm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchossimulatorarm64/1.9.0/annotation-watchossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchossimulatorarm64/1.9.0/annotation-watchossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchossimulatorarm64/1.9.0/annotation-watchossimulatorarm64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosx64/1.9.0/annotation-watchosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosx64/1.9.0/annotation-watchosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosx64/1.9.0/annotation-watchosx64-1.9.0.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosx64",
        "version": "1.9.0"
      }
    }
  ]
}