{
  "formatVersion": "1.1",
  "component": {
    "group": "io.getstream",
    "module": "stream-webrtc-android",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "stream-webrtc-android-1.2.2.aar",
          "url": "stream-webrtc-android-1.2.2.aar",
          "size": 19353452,
          "sha512": "a00d0bd14f10885952607daae200cf1f2328a59d284ca71d6d6abc0e73990ff2b92bea68b57694f6edc7ef3f106c8096e59f330f9f9986503895ed4834597e59",
          "sha256": "394499a42f248ad10ad1962fea1fe8aef613d557669046f6962a04a1bc96c6fd",
          "sha1": "e7379d1790975e100cb863eaa74ebeed2da44bd5",
          "md5": "dec319766092b70a5463bd3b764bfe3a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "stream-webrtc-android-1.2.2.aar",
          "url": "stream-webrtc-android-1.2.2.aar",
          "size": 19353452,
          "sha512": "a00d0bd14f10885952607daae200cf1f2328a59d284ca71d6d6abc0e73990ff2b92bea68b57694f6edc7ef3f106c8096e59f330f9f9986503895ed4834597e59",
          "sha256": "394499a42f248ad10ad1962fea1fe8aef613d557669046f6962a04a1bc96c6fd",
          "sha1": "e7379d1790975e100cb863eaa74ebeed2da44bd5",
          "md5": "dec319766092b70a5463bd3b764bfe3a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "stream-webrtc-android-1.2.2-sources.jar",
          "url": "stream-webrtc-android-1.2.2-sources.jar",
          "size": 610423,
          "sha512": "7ea97a3af919fc9a4e888d18fbbafbe9e6225e492b50f41f2207c120a3da519d19c996edcc39e53911d1d189178679bddf38326daf0c274b37c75806f2db80d0",
          "sha256": "f072cc54d7b063a2d6e4ab7b2c9b6843192e6fc8398135e209aab18056e96ad4",
          "sha1": "95b45d4f240ea5425a3ef9a4d970e1346da58a71",
          "md5": "aca53c47b59bd43e6bebcf09c0c5ead4"
        }
      ]
    }
  ]
}
