{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.9.0/annotation-1.9.0.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.9.0.jar",
          "url": "annotation-jvm-1.9.0.jar",
          "size": 60273,
          "sha512": "9414ce0719dfb3b6f3fb720527a5928dde36d8f3b01ebe0b2d5c9b1837c09f4176d3be0ebef745e4eb06a7f6da3b7a23a55494ee6751e583e871acaf480fea52",
          "sha256": "3236e1e44c41da378c1ac9b515bee0501d8dc512991465100acb4dfe64059a4e",
          "sha1": "3a2db038d9b614a6be762cb37e84bbf2bef69cfa",
          "md5": "cce6eb7b7b435d717234e4d2576a6dfe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.9.0.jar",
          "url": "annotation-jvm-1.9.0.jar",
          "size": 60273,
          "sha512": "9414ce0719dfb3b6f3fb720527a5928dde36d8f3b01ebe0b2d5c9b1837c09f4176d3be0ebef745e4eb06a7f6da3b7a23a55494ee6751e583e871acaf480fea52",
          "sha256": "3236e1e44c41da378c1ac9b515bee0501d8dc512991465100acb4dfe64059a4e",
          "sha1": "3a2db038d9b614a6be762cb37e84bbf2bef69cfa",
          "md5": "cce6eb7b7b435d717234e4d2576a6dfe"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotation-jvm-1.9.0-sources.jar",
          "url": "annotation-jvm-1.9.0-sources.jar",
          "size": 71470,
          "sha512": "30a16d9b4ff9466e1de314c02f0e61e8cdc42596cddff855ad9d254f1e6f589a01fb114abd02ff3265289301d02bfd6f0faae52e8c236002ab871a3338ea72dd",
          "sha256": "3ba0328f55b26c5a1a736fa07bbeaaddaa47477d88954aaa88bcd96dfa7761e5",
          "sha1": "b64ac6d9b039d1a04e4eef03e6676fb55eba0b3f",
          "md5": "8af2a45f0867376ef653cb8029235112"
        }
      ]
    }
  ]
}