{
  "formatVersion": "1.1",
  "component": {
    "group": "phonepe.intentsdk.android.release",
    "module": "IntentSDK",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "IntentSDK-5.3.0.aar",
          "url": "IntentSDK-5.3.0.aar",
          "size": 239287,
          "sha512": "e5383f72c393bb5ea424a7f3d7072401f89e0a97e3765bc1af15b4a19591adf9a981f67a9c3dafc33c6a333a3108c9fd180a5b23794e06a29401feabdb9de285",
          "sha256": "be83e6a2bb37cd61e635faaa1fb287a423472a1daaa181271e64e5fee7c9a7ad",
          "sha1": "e78c773477248a2d8948af191f2feb26f0687301",
          "md5": "108f526fa324ab36fbc38985d30324fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "IntentSDK-5.3.0.aar",
          "url": "IntentSDK-5.3.0.aar",
          "size": 239287,
          "sha512": "e5383f72c393bb5ea424a7f3d7072401f89e0a97e3765bc1af15b4a19591adf9a981f67a9c3dafc33c6a333a3108c9fd180a5b23794e06a29401feabdb9de285",
          "sha256": "be83e6a2bb37cd61e635faaa1fb287a423472a1daaa181271e64e5fee7c9a7ad",
          "sha1": "e78c773477248a2d8948af191f2feb26f0687301",
          "md5": "108f526fa324ab36fbc38985d30324fc"
        }
      ]
    }
  ]
}
