{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-1.6.8-multiplatform-sources.jar",
          "url": "ui-text-1.6.8-multiplatform-sources.jar",
          "size": 341313,
          "sha512": "7cae47d467e53ae50e440cb67b42ca38a917d4394956b9f8b8086e5f754de353c72ed42b72278e595ac697c8d790b93b1b52f735a5a245482eed3a6484d4ddea",
          "sha256": "3517426ab2c252ff2fcd24774df9cc73850961188244d5706947f13131ce23dd",
          "sha1": "0cb871d721e66f6fddb677eb960a0be89945d3b6",
          "md5": "1fbf78e13c7933b97509449b2a3c430b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-text-1.6.8-versionMetadata.json",
          "size": 105333,
          "sha512": "aa01391216af23bc11fbad0eecf08db630b7ede2feee48f7a2963d544df3fc545183664ebbef8c56363dd1076441e56a2ef7d04b22873995846bc7a5cb94c886",
          "sha256": "03c714be800408dddf37eef3646e62899d195979f7dfb1321c09ec9f85ab3abc",
          "sha1": "186c7f161b47e875ca7c11043f2c77e3c7e82b85",
          "md5": "59c9fbba41d8ac9798585b9f09f2924f"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.8"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-metadata-1.6.8.jar",
          "url": "ui-text-1.6.8.jar",
          "size": 730,
          "sha512": "99f1dbca964531ab8d903f9bb2786c1455716c7ee693b5c879b55e783e52e5dd1424086d27592593dd3b4194fbfdfe3dee3da4856e79a4cb90cad5a27ca20517",
          "sha256": "d2a6ee7e58a3586e399991fadfd4d09f2304787384d51c9ec87b62fc46e922d4",
          "sha1": "bc0a6b04c9333228f516418e8827f2f8ae978da3",
          "md5": "46464f8056bbcfd2f469b1e56f7856ab"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-kotlin-1.6.8-sources.jar",
          "url": "ui-text-1.6.8-sources.jar",
          "size": 171130,
          "sha512": "6d880c3ac058304aec08889b777edeab5f4427db208a416d3d6eaae862f93b088e4ade5bb258191a8e7db7fb81ad0db4f0e638e7dd879f95c79a2d916c011acd",
          "sha256": "a865bdc68d089baf8d45754734a7746de7771b89a690dbd8a54d43da5dc6d79c",
          "sha1": "916bd46f848cbd6a9b070d3d0959c4206e97109f",
          "md5": "523dc1df339eb21744ec36babff9194b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-text-android/1.6.8/ui-text-android-1.6.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-text-android",
        "version": "1.6.8"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-text-android/1.6.8/ui-text-android-1.6.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-text-android",
        "version": "1.6.8"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-text-android/1.6.8/ui-text-android-1.6.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-text-android",
        "version": "1.6.8"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-text-desktop/1.6.8/ui-text-desktop-1.6.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-text-desktop",
        "version": "1.6.8"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-text-desktop/1.6.8/ui-text-desktop-1.6.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-text-desktop",
        "version": "1.6.8"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-text-desktop/1.6.8/ui-text-desktop-1.6.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-text-desktop",
        "version": "1.6.8"
      }
    }
  ]
}