{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.6.8.aar",
          "url": "runtime-livedata-1.6.8.aar",
          "size": 7403,
          "sha512": "f7408bdd8bcd7102ab3254c107113a57a9887b92fd6070a9ef63607e690fceb9eb6ebd3edd37ef317088c0f169accf3432f34c382b679236c136be349ad0a907",
          "sha256": "17f87f5a5c12006048841fc705932a512b91b6cb59cf8cf609077bfa7a10210d",
          "sha1": "cc6d6b437f1c524043be381e5acc0c25773898fe",
          "md5": "11ea9a37de571d084dcc96872bd85cfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.6.8.aar",
          "url": "runtime-livedata-1.6.8.aar",
          "size": 7403,
          "sha512": "f7408bdd8bcd7102ab3254c107113a57a9887b92fd6070a9ef63607e690fceb9eb6ebd3edd37ef317088c0f169accf3432f34c382b679236c136be349ad0a907",
          "sha256": "17f87f5a5c12006048841fc705932a512b91b6cb59cf8cf609077bfa7a10210d",
          "sha1": "cc6d6b437f1c524043be381e5acc0c25773898fe",
          "md5": "11ea9a37de571d084dcc96872bd85cfd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.6.8-sources.jar",
          "url": "runtime-livedata-1.6.8-sources.jar",
          "size": 1992,
          "sha512": "921f705367b36a47386ac16864c6cdaa10d6da39e0223a7869a44b285cf500752dd51238e3d7fd9401bc9d9f103e4c1fb01b1df9b196e2e449e1ccdc2793d04d",
          "sha256": "4c9f1c2f9bdb6de160c07e2f1d04268925277095ef3f52ac5924d44dfbe2e036",
          "sha1": "a63d4d8a7fb5bef709f0a247c506dad559edc43c",
          "md5": "43d251b67c20effd8e4f371211ddb5f9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.8"
          },
          "reason": "runtime-livedata is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.6.8-versionMetadata.json",
          "url": "runtime-livedata-1.6.8-versionMetadata.json",
          "size": 284,
          "sha512": "84be62a9d5b9ae97907793a8ebc87c0e448a91f4c4ae42d67f53c45630e66205ef0d17759b22d7703349c32ea815f6a6dc6c01f469a670dc988001993ed7b109",
          "sha256": "fbac9e8cadc58948ce62b5a4f57b1700d6ac2d79c29371d346ee273f482211aa",
          "sha1": "a6cce6afecc6f4576261fe75c49484ad67558892",
          "md5": "20870ca81c05496ed1ba581d877a5745"
        }
      ]
    }
  ]
}